apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: featuregates.poc.kubevirt.io
spec:
  group: poc.kubevirt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: object
                  properties:
                    features:
                      type: object
                      additionalProperties: true
                      x-kubernetes-preserve-unknown-fields: true
                      # let's limit the number of featureGates so nobody can cause the
                      # object to explode
                      maxProperties: 20
                      properties:
                        featureA:
                            type: boolean
                            nullable: true
                            description: "Feature A [Alpha since v1.21]"
                            default: null
                        featureB:
                          type: boolean
                          nullable: true
                          description: "Feature B [Beta since v1.21]"
                          default: true
                        # featureC is GA so setting it to false would warn
                        featureC:
                          type: boolean
                          nullable: true
                          description: |
                            Feature C [GA since v1.21]
                            Note: This featureGate is deprecated and will be removed with v1.23. 
                            This means the feature will be enabled permanently.
                          default: true
                        featureD:
                            type: boolean
                            nullable: true
                            description: "Feature D [Alpha since v1.21]"
                            default: null
  scope: Namespaced
  names:
    plural: featuregates
    singular: featuregate
    kind: FeatureGate
    shortNames:
    - ftg